server:
  port: 8083
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringBoot-dev
    username: "postgres"
    password: "justForLearn"


logging:
  level:
    org.springframework.web: DEBUG