server:
  port: 8083
  servlet:
    context-path: /api

springdoc:
  show-login-endpoint: true
spring:
  security:
    user:
      name: amine
      password: amine
      roles: ADMIN
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringBoot-dev
    username: "postgres"
    password: "justForLearn"


logging:
  level:
    org.springframework.web: WARN